#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MovieApp.Resource", IsApplication=true)]

namespace MovieApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MovieApp.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MovieApp.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int pref_sort_entries = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int pref_sort_values = 2131230721;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070001
			public const int movie_dark_green = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int movie_green = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_star_big_off = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_star_big_on = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int star = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0016
			public const int action_settings = 2131427350;
			
			// aapt resource value: 0x7f0b0002
			public const int favorite = 2131427330;
			
			// aapt resource value: 0x7f0b0015
			public const int fragment_main = 2131427349;
			
			// aapt resource value: 0x7f0b0006
			public const int moviePoster = 2131427334;
			
			// aapt resource value: 0x7f0b0000
			public const int movie_detail_container = 2131427328;
			
			// aapt resource value: 0x7f0b0008
			public const int plot_label = 2131427336;
			
			// aapt resource value: 0x7f0b0007
			public const int plot_layout = 2131427335;
			
			// aapt resource value: 0x7f0b0009
			public const int plot_text = 2131427337;
			
			// aapt resource value: 0x7f0b0014
			public const int poster_grid = 2131427348;
			
			// aapt resource value: 0x7f0b0005
			public const int poster_layout = 2131427333;
			
			// aapt resource value: 0x7f0b000b
			public const int rating_label = 2131427339;
			
			// aapt resource value: 0x7f0b000a
			public const int rating_layout = 2131427338;
			
			// aapt resource value: 0x7f0b000c
			public const int rating_text = 2131427340;
			
			// aapt resource value: 0x7f0b000e
			public const int releaseDate_label = 2131427342;
			
			// aapt resource value: 0x7f0b000d
			public const int releaseDate_layout = 2131427341;
			
			// aapt resource value: 0x7f0b000f
			public const int releaseDate_text = 2131427343;
			
			// aapt resource value: 0x7f0b0012
			public const int review_label = 2131427346;
			
			// aapt resource value: 0x7f0b0011
			public const int review_layout = 2131427345;
			
			// aapt resource value: 0x7f0b0013
			public const int review_text = 2131427347;
			
			// aapt resource value: 0x7f0b0003
			public const int title_label = 2131427331;
			
			// aapt resource value: 0x7f0b0001
			public const int title_layout = 2131427329;
			
			// aapt resource value: 0x7f0b0004
			public const int title_text = 2131427332;
			
			// aapt resource value: 0x7f0b0010
			public const int trailer_layout = 2131427344;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_detail = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fragment_detail = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fragment_main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int main = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int action_settings = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int app_name = 2131099651;
			
			// aapt resource value: 0x7f060015
			public const int content_authority = 2131099669;
			
			// aapt resource value: 0x7f060002
			public const int hello = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int plot_label = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int plot_text = 2131099655;
			
			// aapt resource value: 0x7f060011
			public const int pref_sortDialog_label = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int pref_sort_default = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int pref_sort_key = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int pref_sort_label = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int pref_sort_summary = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int rating_label = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int rating_text = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int releaseDate_label = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int releaseDate_text = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int review_label = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int review_text = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int title_label = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int title_text = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int trailer_label = 2131099660;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int pref_general = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
