#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MovieApp.Resource", IsApplication=true)]

namespace MovieApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int pref_sort_entries = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int pref_sort_values = 2131165185;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int monoandroidsplash = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0011
			public const int action_settings = 2131361809;
			
			// aapt resource value: 0x7f0a0000
			public const int container = 2131361792;
			
			// aapt resource value: 0x7f0a0010
			public const int fragment_poster = 2131361808;
			
			// aapt resource value: 0x7f0a0005
			public const int moviePoster = 2131361797;
			
			// aapt resource value: 0x7f0a0007
			public const int plot_label = 2131361799;
			
			// aapt resource value: 0x7f0a0006
			public const int plot_layout = 2131361798;
			
			// aapt resource value: 0x7f0a0008
			public const int plot_text = 2131361800;
			
			// aapt resource value: 0x7f0a000f
			public const int poster_grid = 2131361807;
			
			// aapt resource value: 0x7f0a0004
			public const int poster_layout = 2131361796;
			
			// aapt resource value: 0x7f0a000a
			public const int rating_label = 2131361802;
			
			// aapt resource value: 0x7f0a0009
			public const int rating_layout = 2131361801;
			
			// aapt resource value: 0x7f0a000b
			public const int rating_text = 2131361803;
			
			// aapt resource value: 0x7f0a000d
			public const int releaseDate_label = 2131361805;
			
			// aapt resource value: 0x7f0a000c
			public const int releaseDate_layout = 2131361804;
			
			// aapt resource value: 0x7f0a000e
			public const int releaseDate_text = 2131361806;
			
			// aapt resource value: 0x7f0a0002
			public const int title_label = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int title_layout = 2131361793;
			
			// aapt resource value: 0x7f0a0003
			public const int title_text = 2131361795;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_detail = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fragment_detail = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fragment_main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int main = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000a
			public const int action_settings = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int plot_label = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int plot_text = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int pref_sortDialog_label = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int pref_sort_default = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int pref_sort_key = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int pref_sort_label = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int pref_sort_summary = 2131099662;
			
			// aapt resource value: 0x7f060006
			public const int rating_label = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int rating_text = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int releaseDate_label = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int releaseDate_text = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int title_label = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int title_text = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Mono_Android_Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int pref_general = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
